### PR TITLE
Add optional error handler for QueuingMetricSink

### PR DESCRIPTION
**Pull request by mlowicki**
https://github.com/56quarters/cadence/issues/194

### CODE REVIEW

**Comment by mlowicki** [comment]
It does not contain doc comments yet - will add those once we agree on the approach.

**Review by 56quarters — COMMENTED** [review]
Thanks! This pattern seems backwards from how I've usually seen builders work.

Could you rework this to use a similar pattern to the `StatsdClientBuilder`. I.e.

```rust
impl QueuingMetricSink {
    pub fn builder() -> QueuingMetricSinkBuilder { ... }
    
    pub fn new(sink) -> Self {
        Self::builder().build(sink)
     }
     
     pub fn with_capacity(sink, cap) -> Self {
         Self::builder().with_capacity(cap).build(sink)
      }
}

impl QueuingMetricSinkBuilder {
    pub fn with_capacity(self, cap) -> Self { ... }
    
    pub fn with_error_handler(self, f) -> Self { ... }
    
    pub fn build(self) -> QueuingMetricSink { ... }
}
```

**Comment by mlowicki** [comment]
> Thanks! This pattern seems backwards from how I've usually seen builders work.
> 
> Could you rework this to use a similar pattern to the `StatsdClientBuilder`. I.e.
> 
> ```rust
> impl QueuingMetricSink {
>     pub fn builder() -> QueuingMetricSinkBuilder { ... }
>     
>     pub fn new(sink) -> Self {
>         Self::builder().build(sink)
>      }
>      
>      pub fn with_capacity(sink, cap) -> Self {
>          Self::builder().with_capacity(cap).build(sink)
>       }
> }
> 
> impl QueuingMetricSinkBuilder {
>     pub fn with_capacity(self, cap) -> Self { ... }
>     
>     pub fn with_error_handler(self, f) -> Self { ... }
>     
>     pub fn build(self) -> QueuingMetricSink { ... }
> }
> ```

yea, sounds good - done.

**Comment by 56quarters** [comment]
Looks awesome, I'll review and merge later today. Thanks!

**Review by 56quarters — APPROVED** [review]
LGTM, thanks!

**Comment by 56quarters** [comment]
> Any plans for releasing new version?

Sure, I'll try to get 1.2 out this week.

**Pull request merged**
