### PR TITLE
Add support for sampling metrics

### LINKED ISSUE #179: Support being able to sample metrics
Following up as requested from https://github.com/56quarters/cadence/issues/6 😊 

The way I'd like to see sampling implement is a combination of the two options proposed at the end of that ticket. The server sampling (that sends `@0.1`) tells the server that you are only taking and sending a random sample. That is, the server should expect that at `@0.1`, if you sent ten metrics, in reality there were a hundred metrics, just you only sent a random selection instead of the whole lot.

This is where the second option comes in to play. If we give a sample a rate of `0.1` or `0.01` or even `0.0001`, then that is also the rate at which we should collect the metric. For example, my use case is monitoring how much data is being written and read through a socket. This would mean capturing a metric after every read and write, of which there will tens of thousands per second if we weren't sampling. With a sample rate of `0.01` instead of ten thousand, we'd get one hundred instead - a much lower, but still perfectly usable amount.

The sampling rate should be able to be set per metric call. A c statsd library uses something like this:

```
counter_increment("my.app", 10, 0.01);
```

Here the first thing `counter_increment` does is call `rand()` and compares the result to the sample rate given. If it matches, it will go ahead and report the metric. If it doesn't match, the function is effectively a noop.

The two suggestions for extra performance in https://github.com/56quarters/cadence/issues/6 are perfectly valid. I am using the  `BufferedUdpMetricSink` but although this does prevent one stat per packet, it will still ultimately send a large number of stats. It is true that I could keep a counter in my app and only send it on a timer say, but part of the beauty of statsd is not having to do that - you can simply add your metrics where you want them, set your sample rate (so you don't melt anything) and that's it - no complex state to worry about 😊 

Hope this puts us in a good place to start discussions on the feature :)

### PR DESCRIPTION
**Pull request by ianks**
This PR adds some initial support for sampling individual metrics. I made it an opt-in feature in Cargo so folks won't pull in the `rand` dependency by default.

Since I'm new to the codebase, I probably did some things sub-optimally. Let me know I can improve it!

resolves #179

### CODE REVIEW

**Comment by 56quarters** [comment]
Thanks! I'll try to take a first pass over this in a bit.

**Comment by ianks** [comment]
I messed around with a slight refactor of this PR which tries a slightly different approach by moving the sampling behavior to a new type. LMK which you prefer:

```diff
diff --git i/cadence/src/types.rs w/cadence/src/types.rs
index 3ececec..ee4c227 100644
--- i/cadence/src/types.rs
+++ w/cadence/src/types.rs
@@ -8,6 +8,7 @@
 // option. This file may not be copied, modified, or distributed
 // except according to those terms.
 
+use crate::builder::SampleRate;
 use crate::builder::{MetricFormatter, MetricValue};
 use std::error;
 use std::fmt;
@@ -19,6 +20,76 @@ use std::io;
 /// types of metrics as defined in the [Statsd spec](https://github.com/b/statsd_spec).
 pub trait Metric {
     fn as_metric_str(&self) -> &str;
+
+    fn is_sampled(&self) -> bool {
+        true
+    }
+}
+
+/// Marker trait for metrics that can be sampled.
+///
+/// > A float between 0 and 1, inclusive. Only works with COUNT, HISTOGRAM,
+/// > DISTRIBUTION, and TIMER metrics. The default is 1, which samples 100% of the
+/// > time.
+/// > - via [DataDog](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell)
+pub trait Sampleable: Metric {
+    /// Returns a new metric that indicates this metric was sampled.
+    fn sampled(self, sample_rate: f32) -> Result<Sampled<Self>, MetricError>
+    where
+        Self: Sized,
+    {
+        Sampled::new(self, sample_rate)
+    }
+}
+
+impl Sampleable for Counter {}
+impl Sampleable for Timer {}
+impl Sampleable for Gauge {}
+impl Sampleable for Histogram {}
+
+/// Wraps a that indicates a metric was sampled.
+pub struct Sampled<T: Sampleable> {
+    is_sampled: bool,
+    repr: String,
+    _marker: std::marker::PhantomData<T>,
+}
+
+impl<T: Sampleable> Sampled<T> {
+    pub fn new<S: TryInto<SampleRate>>(
+        metric: T,
+        sample_rate: S,
+    ) -> Result<Self, <S as std::convert::TryInto<SampleRate>>::Error> {
+        let sample_rate = sample_rate.try_into()?;
+        let mut repr = String::with_capacity(metric.as_metric_str().len() + sample_rate.kv_size());
+        repr.push_str(metric.as_metric_str());
+        repr.push('|');
+        repr.push_str(sample_rate.as_str());
+
+        #[cfg(feature = "sample-rate")]
+        use rand::Rng;
+
+        #[cfg(feature = "sample-rate")]
+        let is_sampled = rand::thread_rng().gen_bool(sample_rate.value() as f64);
+
+        #[cfg(not(feature = "sample-rate"))]
+        let is_sampled = true;
+
+        Ok(Sampled {
+            repr,
+            is_sampled,
+            _marker: std::marker::PhantomData,
+        })
+    }
+}
+
+impl<T: Sampleable> Metric for Sampled<T> {
+    fn as_metric_str(&self) -> &str {
+        &self.repr
+    }
+
+    fn is_sampled(&self) -> bool {
+        self.is_sampled
+    }
 }
 
 /// Counters are simple values incremented or decremented by a client.
@@ -307,7 +378,7 @@ pub type MetricResult<T> = Result<T, MetricError>;
 mod tests {
     #![allow(deprecated, deprecated_in_future)]
 
-    use super::{Counter, ErrorKind, Gauge, Histogram, Meter, Metric, MetricError, Set, Timer};
+    use super::{Counter, ErrorKind, Gauge, Histogram, Meter, Metric, MetricError, Sampleable, Set, Timer};
     use std::error::Error;
     use std::io;
 
@@ -421,4 +492,17 @@ mod tests {
         let our_err = MetricError::from((ErrorKind::InvalidInput, "Nope!"));
         assert!(our_err.source().is_none());
     }
+
+    #[test]
+    fn test_metrics_can_be_wrapped_as_sampled() {
+        let counter = Counter::new("my.app.", "test.counter", 4).sampled(1.0 / 3.0).unwrap();
+        let gauge = Gauge::new("my.app.", "test.gauge", 2).sampled(0.5).unwrap();
+        let histogram = Histogram::new("my.app.", "test.histogram", 45).sampled(0.5).unwrap();
+        let timer = Timer::new("my.app.", "test.timer", 34).sampled(0.5).unwrap();
+
+        assert_eq!("my.app.test.counter:4|c|@0.33333", counter.as_metric_str());
+        assert_eq!("my.app.test.timer:34|ms|@0.5", timer.as_metric_str());
+        assert_eq!("my.app.test.gauge:2|g|@0.5", gauge.as_metric_str());
+        assert_eq!("my.app.test.histogram:45|h|@0.5", histogram.as_metric_str());
+    }
 }
```

**Comment by ianks** [comment]
100% agree. Most folks will have it in their dep tree already, anyway I imagine.

**Review by 56quarters — CHANGES_REQUESTED** [review]
The public API for this roughly looks how I want, thanks! There are a few changes I'd like to see with how this is implemented that fall into a few categories:

* I'd like to propagate errors related to bad sample rates instead of panicking or ignoring them.
* `ByteStr` is a nice touch but I'd rather do something simpler/dumber and use float formatting for `write!()` with a fixed number of digits.
* Removing the feature flag as discussed and combining the no-op and rand based `Sampler`s.

I think once the above changes are made, there might be further changes we could make to simplify this a bit. Thanks again for this feature!

**Comment by 56quarters** [comment]
> I messed around with a slight refactor of this PR which tries a slightly different approach by moving the sampling behavior to a new type. LMK which you prefer:

My preference would be for the original implementation, adding a `.with_sample_rate()` method to `MetricBuilder`. It feels more natural to me that you can only add sampling when you're "building" a metric to send, rather than applying a sample after a `Metric` (`Counter`, `Gauge`, etc) has already been constructed.

**Comment by 56quarters** [comment]
Closing this in favor of #211 which adds sampling but requires that it happens outside of calls to Cadence.

**Pull request closed without merging**
